version: '3.8'
services:
  database:
    container_name: ifidie-pg
    build:
      dockerfile: Dockerfile
      context: "./postgres"
    restart: always
    environment:
      - POSTGRES_DB=IFIDIE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6000:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local