version: '3.8'
services:
  ifidie-dev-api:
    container_name: ifidie-dev-api
    build:
      context: "../"
      dockerfile: deployments-dev/api/Dockerfile
    environment:
      - CONFIG_FILE_NAME=config-dev
      - CONFIG_FILE_TYPE=yaml
      - CONFIG_FILE_PATH=.
    ports:
      - '5501:8080'
    volumes:
      - ../:/go/src/ifidie_backend

  ifidie-dev-pg:
    container_name: ifidie-dev-pg
    build:
      context: "./postgres"
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=IFIDIE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6501:5432'
    volumes: 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql